// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzY5HDYYhYPJV5XmAsZBIn3GuB8LCikPs',
    appId: '1:90744923485:web:9fa2665e8658e8e58b74b4',
    messagingSenderId: '90744923485',
    projectId: 'wellnessapp-d990b',
    authDomain: 'wellnessapp-d990b.firebaseapp.com',
    storageBucket: 'wellnessapp-d990b.firebasestorage.app',
    measurementId: 'G-XZCWSGHBDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnX2CSmxhhOkRCtSG8l4sC7u4kBf2RFnE',
    appId: '1:90744923485:android:8ecf7a60d86e49b68b74b4',
    messagingSenderId: '90744923485',
    projectId: 'wellnessapp-d990b',
    storageBucket: 'wellnessapp-d990b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRliJNWEpBJ-qUbclO5OQF5Ln3ZCUa5Ew',
    appId: '1:90744923485:ios:43862ab7605081c78b74b4',
    messagingSenderId: '90744923485',
    projectId: 'wellnessapp-d990b',
    storageBucket: 'wellnessapp-d990b.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRliJNWEpBJ-qUbclO5OQF5Ln3ZCUa5Ew',
    appId: '1:90744923485:ios:43862ab7605081c78b74b4',
    messagingSenderId: '90744923485',
    projectId: 'wellnessapp-d990b',
    storageBucket: 'wellnessapp-d990b.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzY5HDYYhYPJV5XmAsZBIn3GuB8LCikPs',
    appId: '1:90744923485:web:5495aa059423c7a48b74b4',
    messagingSenderId: '90744923485',
    projectId: 'wellnessapp-d990b',
    authDomain: 'wellnessapp-d990b.firebaseapp.com',
    storageBucket: 'wellnessapp-d990b.firebasestorage.app',
    measurementId: 'G-50XGQJN054',
  );
}
